// gateway/ui/src/components/Mappings.tsx
import { useCallback, useEffect, useState } from "react";
import type { Api, Mapping } from "../api";
import { fmtTime } from "../util";
import { Reveal } from "./Reveal";

export function Mappings({ api, status }: { api: Api; status: (msg: string, isError?: boolean) => void }) {
  const [scope, setScope] = useState("");
  const [items, setItems] = useState<Mapping[]>([]);

  const load = useCallback(
    async (withScope: string) => {
      try {
        const data = await api.get<{ items: Mapping[] }>(
          "/audit/mappings" + (withScope ? "?scope=" + encodeURIComponent(withScope) : ""),
        );
        setItems(data.items);
        status(data.items.length + " mappings");
      } catch (e) {
        status((e as Error).message, true);
      }
    },
    [api, status],
  );

  useEffect(() => {
    load("");
  }, [load]);

  return (
    <div className="panel">
      <h3>Pseudonym mappings</h3>
      <div className="row" style={{ marginBottom: 12 }}>
        <input
          placeholder="scope e.g. session:key-ab12 or global"
          size={34}
          value={scope}
          onChange={(e) => setScope(e.target.value)}
        />
        <button className="primary" onClick={() => load(scope.trim())}>
          Load
        </button>
      </div>
      <table className="grid">
        <thead>
          <tr>
            <th>scope</th>
            <th>category</th>
            <th>original (was)</th>
            <th>pseudonym (now)</th>
            <th>created</th>
          </tr>
        </thead>
        <tbody>
          {items.map((m, i) => (
            <tr key={i}>
              <td className="mono">{m.scope}</td>
              <td>
                <span className="kind">{m.entity_type}</span>
              </td>
              <td className="mono">
                <del className="red">
                  <Reveal>{m.original}</Reveal>
                </del>
              </td>
              <td className="mono">
                <ins className="green">{m.pseudonym}</ins>
              </td>
              <td>{fmtTime(m.created_at)}</td>
            </tr>
          ))}
          {!items.length && (
            <tr>
              <td colSpan={5} className="empty-state">
                No mappings.
              </td>
            </tr>
          )}
        </tbody>
      </table>
    </div>
  );
}

// gateway/ui/src/pages/Mappings.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import type { Api, Mapping } from "../lib/api";
  import { fmtTime } from "../lib/format";

  let { api, status }: { api: Api; status: (msg: string, isError?: boolean) => void } = $props();

  let items = $state<Mapping[]>([]);
  let reveal = $state(false);
  let scope = $state("");
  let search = $state("");

  async function load(): Promise<void> {
    try {
      const params = scope ? `?scope=${encodeURIComponent(scope)}` : "";
      items = (await api.get<{ items: Mapping[] }>("/audit/mappings" + params)).items;
      status("");
    } catch (error) {
      status((error as Error).message, true);
    }
  }

  const filtered = $derived(
    items.filter((item) => {
      const needle = search.trim().toLowerCase();
      return !needle || item.original.toLowerCase().includes(needle) || item.pseudonym.toLowerCase().includes(needle);
    }),
  );

  onMount(load);
</script>

<div class="page">
  <div class="toolbar">
    <input placeholder="scope (session:… or global)" bind:value={scope} onkeydown={(e) => e.key === "Enter" && load()} />
    <button class="primary" onclick={load}>Load scope</button>
    <input placeholder="search" bind:value={search} />
    <label class="check"><input type="checkbox" bind:checked={reveal} /> reveal originals</label>
    <div class="spacer"></div>
    <span class="muted">{filtered.length} mappings</span>
  </div>

  <div class="table-scroll">
    <table class="grid">
      <thead><tr><th>scope</th><th>type</th><th>original</th><th>pseudonym</th><th>created</th></tr></thead>
      <tbody>
        {#each filtered as item (item.scope + item.entity_type + item.pseudonym)}
          <tr>
            <td class="mono">{item.scope}</td>
            <td>{item.entity_type}</td>
            <td class="mono wrap" class:blur={!reveal}>{item.original}</td>
            <td class="mono wrap">{item.pseudonym}</td>
            <td class="muted">{fmtTime(item.created_at)}</td>
          </tr>
        {:else}
          <tr><td colspan="5" class="empty-state">No mappings.</td></tr>
        {/each}
      </tbody>
    </table>
  </div>
</div>
