// gateway/ui/src/components/Overrides.tsx
import { useCallback, useEffect, useState } from "react";
import type { Api, Override } from "../api";
import { fmtTime } from "../util";
import { Reveal } from "./Reveal";

export function Overrides({ api, status }: { api: Api; status: (msg: string, isError?: boolean) => void }) {
  const [items, setItems] = useState<Override[]>([]);
  const [kind, setKind] = useState("category");
  const [category, setCategory] = useState("");
  const [value, setValue] = useState("");
  const [minutes, setMinutes] = useState(60);
  const [permanent, setPermanent] = useState(false);
  const [note, setNote] = useState("");

  const load = useCallback(async () => {
    try {
      const data = await api.get<{ items: Override[] }>("/audit/overrides");
      setItems(data.items);
    } catch (e) {
      status((e as Error).message, true);
    }
  }, [api, status]);

  useEffect(() => {
    load();
  }, [load]);

  const add = async () => {
    if (!category.trim()) {
      status("category is required", true);
      return;
    }
    try {
      await api.post("/audit/overrides", {
        kind,
        category: category.trim(),
        value: value.trim() || null,
        minutes: permanent ? null : minutes,
        permanent,
        note: note.trim() || null,
      });
      status("override added");
      setValue("");
      setNote("");
      load();
    } catch (e) {
      status((e as Error).message, true);
    }
  };

  const revoke = async (id: number) => {
    try {
      await api.del("/audit/overrides/" + id);
      load();
    } catch (e) {
      status((e as Error).message, true);
    }
  };

  return (
    <div className="panel">
      <h3>Allow data through temporarily</h3>
      <p className="muted">
        A category override lets a whole finding type pass through unchanged (still logged as "allowed"). A value
        override lets one specific original value pass through for a category.
      </p>
      <div className="row" style={{ marginBottom: 14 }}>
        <select value={kind} onChange={(e) => setKind(e.target.value)}>
          <option value="category">category</option>
          <option value="value">value</option>
        </select>
        <input
          placeholder="category e.g. PERSON, EMAIL_ADDRESS, secrets"
          size={34}
          value={category}
          onChange={(e) => setCategory(e.target.value)}
        />
        <input
          placeholder="value (for kind=value)"
          size={26}
          value={value}
          onChange={(e) => setValue(e.target.value)}
          disabled={kind !== "value"}
        />
        <label className="muted row" style={{ gap: 6 }}>
          minutes
          <input
            type="number"
            min={1}
            style={{ width: 90 }}
            value={minutes}
            onChange={(e) => setMinutes(parseInt(e.target.value, 10) || 0)}
            disabled={permanent}
          />
        </label>
        <label className="muted row" style={{ gap: 6 }}>
          <input type="checkbox" checked={permanent} onChange={(e) => setPermanent(e.target.checked)} /> permanent
        </label>
        <input placeholder="note" size={20} value={note} onChange={(e) => setNote(e.target.value)} />
        <button className="primary" onClick={add}>
          Add override
        </button>
      </div>
      <table className="grid">
        <thead>
          <tr>
            <th>id</th>
            <th>kind</th>
            <th>category</th>
            <th>value</th>
            <th>expires</th>
            <th>state</th>
            <th>note</th>
            <th />
          </tr>
        </thead>
        <tbody>
          {items.map((o) => (
            <tr key={o.id}>
              <td>{o.id}</td>
              <td>{o.kind}</td>
              <td><span className="kind">{o.category}</span></td>
              <td className="mono">
                {o.value_display ? (
                  <Reveal>{o.value_display}</Reveal>
                ) : (
                  <span className="muted">—</span>
                )}
              </td>
              <td>{o.expires_at ? fmtTime(o.expires_at) : "until revoked"}</td>
              <td className={o.active ? "act act-allowed" : "muted"}>{o.active ? "active" : "expired"}</td>
              <td>{o.note || ""}</td>
              <td>
                <button className="danger" onClick={() => revoke(o.id)}>
                  revoke
                </button>
              </td>
            </tr>
          ))}
          {!items.length && (
            <tr>
              <td colSpan={8} className="empty-state">
                No overrides.
              </td>
            </tr>
          )}
        </tbody>
      </table>
    </div>
  );
}

// gateway/ui/src/pages/Overrides.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import type { Api, Override } from "../lib/api";
  import { fmtAgo, fmtTime } from "../lib/format";

  let { api, status }: { api: Api; status: (msg: string, isError?: boolean) => void } = $props();

  let items = $state<Override[]>([]);
  let kind = $state<"category" | "value">("category");
  let category = $state("");
  let value = $state("");
  let minutes = $state(60);
  let permanent = $state(false);
  let note = $state("");

  async function load(): Promise<void> {
    try {
      items = (await api.get<{ items: Override[] }>("/audit/overrides")).items;
      status("");
    } catch (error) {
      status((error as Error).message, true);
    }
  }

  async function create(): Promise<void> {
    if (!category.trim()) {
      status("a category is required", true);
      return;
    }
    try {
      await api.post("/audit/overrides", {
        kind,
        category: category.trim(),
        value: kind === "value" ? value : undefined,
        minutes: permanent ? undefined : minutes,
        permanent,
        note,
      });
      status("override created");
      category = "";
      value = "";
      note = "";
      await load();
    } catch (error) {
      status((error as Error).message, true);
    }
  }

  async function revoke(id: number): Promise<void> {
    try {
      await api.del(`/audit/overrides/${id}`);
      status("override revoked");
      await load();
    } catch (error) {
      status((error as Error).message, true);
    }
  }

  onMount(load);
</script>

<div class="page">
  <div class="card">
    <h4>Allow-through override</h4>
    <div class="form-row">
      <label>Kind
        <select bind:value={kind}><option value="category">category</option><option value="value">exact value</option></select>
      </label>
      <label class="grow">Category / detector<input placeholder="EMAIL_ADDRESS or pii.regex:EMAIL_ADDRESS" bind:value={category} /></label>
      {#if kind === "value"}<label class="grow">Value<input bind:value={value} /></label>{/if}
      <label>Minutes<input type="number" bind:value={minutes} disabled={permanent} /></label>
      <label class="check inline"><input type="checkbox" bind:checked={permanent} /> permanent</label>
    </div>
    <label>Note<input bind:value={note} /></label>
    <div class="row end"><button class="primary" onclick={create}>Create override</button></div>
  </div>

  <div class="card">
    <h4>Overrides ({items.length})</h4>
    {#if items.length}
      <table class="grid">
        <thead><tr><th>kind</th><th>category</th><th>value</th><th>status</th><th>created</th><th></th></tr></thead>
        <tbody>
          {#each items as item (item.id)}
            <tr class:inactive={!item.active}>
              <td>{item.kind}</td>
              <td class="mono">{item.category}</td>
              <td class="mono wrap">{item.value_display ?? "—"}</td>
              <td>
                {#if item.active}<span class="pill good">active</span>{:else}<span class="pill muted">inactive</span>{/if}
                {#if item.expires_at}<div class="muted small">expires {fmtAgo(item.expires_at)}</div>{/if}
              </td>
              <td class="muted">{fmtTime(item.created_at)}</td>
              <td class="right"><button class="danger small" onclick={() => revoke(item.id)}>Revoke</button></td>
            </tr>
          {/each}
        </tbody>
      </table>
    {:else}
      <div class="empty-state">No overrides.</div>
    {/if}
  </div>
</div>
